services:
  verti-grade:
    container_name: verti-grade-app
    image: tilalx/verti-grade:beta
    ports:
      - 8080:8080
    environment:
      - SERVER_URL=https://dav.aelx.de

volumes:
  db_data: