root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./pocketbase ."
entrypoint = "./pocketbase"
args_bin = ["serve", "--http=0.0.0.0:8090"]
include_ext = ["go"]
exclude_dir = ["pb_data", "pb_data_backup", "pb_migrations", "tmp"]
send_interrupt = true
kill_delay = "2s"

[log]
main_only = true
