/// <reference path="../pb_data/types.d.ts" />
migrate(
    (app) => {
        const collection = new Collection({
            createRule: '',
            deleteRule:
                '@request.auth.role.permissions.name ?= "manage_reports"',
            fields: [
                {
                    autogeneratePattern: '[a-z0-9]{15}',
                    hidden: false,
                    id: 'text3208210256',
                    max: 15,
                    min: 15,
                    name: 'id',
                    pattern: '^[a-z0-9]+$',
                    presentable: false,
                    primaryKey: true,
                    required: true,
                    system: true,
                    type: 'text',
                },
                {
                    hidden: false,
                    id: 'select_report_content_type',
                    maxSelect: 1,
                    name: 'content_type',
                    presentable: false,
                    required: true,
                    system: false,
                    type: 'select',
                    values: ['rating', 'route'],
                },
                {
                    autogeneratePattern: '',
                    hidden: false,
                    id: 'text_report_content_id',
                    max: 15,
                    min: 0,
                    name: 'content_id',
                    pattern: '',
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: 'text',
                },
                {
                    autogeneratePattern: '',
                    hidden: false,
                    id: 'text_report_content_url',
                    max: 500,
                    min: 0,
                    name: 'content_url',
                    pattern: '',
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: 'text',
                },
                {
                    autogeneratePattern: '',
                    hidden: false,
                    id: 'text_report_content_snapshot',
                    max: 5000,
                    min: 0,
                    name: 'content_snapshot',
                    pattern: '',
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: 'text',
                },
                {
                    hidden: false,
                    id: 'select_report_reason',
                    maxSelect: 1,
                    name: 'reason',
                    presentable: false,
                    required: true,
                    system: false,
                    type: 'select',
                    values: [
                        'hate_speech',
                        'harassment',
                        'violence_threat',
                        'sexual_content',
                        'personal_data',
                        'ip_infringement',
                        'spam_fraud',
                        'other',
                    ],
                },
                {
                    autogeneratePattern: '',
                    hidden: false,
                    id: 'text_report_explanation',
                    max: 2000,
                    min: 0,
                    name: 'explanation',
                    pattern: '',
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: 'text',
                },
                {
                    autogeneratePattern: '',
                    hidden: false,
                    id: 'text_report_notifier_name',
                    max: 100,
                    min: 0,
                    name: 'notifier_name',
                    pattern: '',
                    presentable: true,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: 'text',
                },
                {
                    exceptDomains: null,
                    hidden: false,
                    id: 'email_report_notifier',
                    name: 'notifier_email',
                    onlyDomains: null,
                    presentable: false,
                    required: true,
                    system: false,
                    type: 'email',
                },
                {
                    hidden: false,
                    id: 'bool_report_good_faith',
                    name: 'good_faith',
                    presentable: false,
                    required: true,
                    system: false,
                    type: 'bool',
                },
                {
                    hidden: false,
                    id: 'select_report_status',
                    maxSelect: 1,
                    name: 'status',
                    presentable: false,
                    required: true,
                    system: false,
                    type: 'select',
                    values: ['open', 'actioned', 'rejected'],
                },
                {
                    hidden: false,
                    id: 'select_report_decision',
                    maxSelect: 1,
                    name: 'decision',
                    presentable: false,
                    required: false,
                    system: false,
                    type: 'select',
                    values: ['content_removed', 'content_kept'],
                },
                {
                    autogeneratePattern: '',
                    hidden: false,
                    id: 'text_report_decision_reason',
                    max: 2000,
                    min: 0,
                    name: 'decision_reason',
                    pattern: '',
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: 'text',
                },
                {
                    hidden: false,
                    id: 'date_report_decided_at',
                    max: '',
                    min: '',
                    name: 'decided_at',
                    presentable: false,
                    required: false,
                    system: false,
                    type: 'date',
                },
                {
                    cascadeDelete: false,
                    collectionId: '_pb_users_auth_',
                    hidden: false,
                    id: 'relation_report_decided_by',
                    maxSelect: 1,
                    minSelect: 0,
                    name: 'decided_by',
                    presentable: false,
                    required: false,
                    system: false,
                    type: 'relation',
                },
                {
                    hidden: false,
                    id: 'bool_report_receipt_sent',
                    name: 'receipt_sent',
                    presentable: false,
                    required: false,
                    system: false,
                    type: 'bool',
                },
                {
                    hidden: false,
                    id: 'date_report_notified_at',
                    max: '',
                    min: '',
                    name: 'notified_at',
                    presentable: false,
                    required: false,
                    system: false,
                    type: 'date',
                },
                {
                    hidden: false,
                    id: 'autodate_report_created',
                    name: 'created',
                    onCreate: true,
                    onUpdate: false,
                    presentable: false,
                    system: false,
                    type: 'autodate',
                },
                {
                    hidden: false,
                    id: 'autodate_report_updated',
                    name: 'updated',
                    onCreate: true,
                    onUpdate: true,
                    presentable: false,
                    system: false,
                    type: 'autodate',
                },
            ],
            id: 'reports_col_id',
            indexes: [
                'CREATE INDEX `idx_reports_content_id` ON `reports` (`content_id`)',
                'CREATE INDEX `idx_reports_status` ON `reports` (`status`)',
                'CREATE INDEX `idx_reports_created` ON `reports` (`created`)',
            ],
            listRule: '@request.auth.role.permissions.name ?= "manage_reports"',
            name: 'reports',
            system: false,
            type: 'base',
            updateRule:
                '@request.auth.role.permissions.name ?= "manage_reports"',
            viewRule: '@request.auth.role.permissions.name ?= "manage_reports"',
        })

        app.save(collection)
    },
    (app) => {
        const collection = app.findCollectionByNameOrId('reports_col_id')
        app.delete(collection)
    },
)
